sina:
  key:    873127458 # iwine
  secret: 422a1373ca21efa5b2a23c95999f16d8
  url:    http://iwine.com
  callback: "http://iwine.com/oauth_login/sina/update_info?"
qq:
  callback: "http://iwine.com/oauth_login/qq/update_info"