development:
  key:    801091917
  secret: 400c5d0f2a08ea78e6e637c402eab604
  url:    http://localhost:3000
  callback: "http://localhost:3000/friends/qq/callback"

production:
  key:    801091917
  secret: 400c5d0f2a08ea78e6e637c402eab604
  url:    http://iwine.com
  callback: "http://iwine.com/friends/qq/callback"