development:
  key:    714234289 # iwine
  secret: 59c06ee13b38b7ca3c0bd8c8fc826ee1
  url:    http://localhost:3000
  callback: "http://localhost:3000/friends/sina/callback"

production:
  key:    714234289 # iwine
  secret: 59c06ee13b38b7ca3c0bd8c8fc826ee1
  url:    http://iwine.com
  callback: "http://iwine.com/friends/sina/callback"
