development:
  key:    3378977054
  secret: c0c3e93126439a890c92460113d683ad
  url:    http://localhost:3000
  callback: "http://localhost:3000/users/syncs/sina/callback"

production:
  key:    3378977054
  secret: c0c3e93126439a890c92460113d683ad
  url:    http://localhost:3000
  callback: "http://localhost:3000/users/syncs/sina/callback"