wines:
  capacity: [750ml, 500ml, 200ml, 其他]
users:
  cellars:
    item:
      location: [北京, 上海, 香港,广州, 深圳, 其他]
user_profile:
  configs:
    defaults:
      normal: 1 #默认分享或者所有人可见
      email: [1, 2, 3]
    normal:
      1: 所有人可见
      2: 我关注的人可见
      3: 仅自己可见
    birth_day:
      1: 公开
      2: 完整显示
      3: 只显示星座
      4: 只显示月日
      5: 保密
    message:
      1: <strong>所有人</strong><span></span>
      2: 可信用户
      3: 我关注的人
    recommend:
      1: 在我附近上网的人
      2: 我的MSN／邮箱联系人
      3: 与我有间接关注的人
      4: 与我有共同好友的人
    email:
      1: 我收到一条私信
      2: 我收到一条回复或评论
      3: 我被某人关注
      4: 我的酒评被收藏
      5: 关于新 iWine 产品功能和技巧的更新
      6: 关于我的 iWine 账号的产品或服务更新
    share:
      1: 默认分享


friends:
  oauth:
    sync_url: /friends/sync
    
# 图片缩略图
image:
  user:
    origin:
      width: 280
      height: 280
    large:
      width: 130
      height: 130
    x_middle:
      width: 100
      height: 100
    middle:
      width: 50
      height: 50
    thumb:
      width: 30
      height: 30

  wine_label:
    thumb:
      width: 100
      height: 100
    middle:
      width: 200
      height: 200
    large:
      width: 400
      height: 400
      
  wine:
    xxx_thumb: 
      width: 50
      height: 50
    xx_thumb:
      width: 70
      height: 70
    x_thumb: 
      width: 100
      height: 100
    thumb: 
      width: 130
      height: 130
    middle:
      width: 200
      height: 200
    large:
      width: 440
      height: 440
      
  winery:
    xxx_thumb: 
       width: 50
       height: 50
    xx_thumb:
       width: 70
       height: 70
    x_thumb:
       width: 100
       height: 100
    thumb: 
       width: 130
       height: 130
    middle:
       width: 200
       height: 200
    middle_x:
       width: 360
       height: 360
    large:
       width: 440
       height: 440
        
timeline:
   event:
    user:
      new_comment: "发表了一条评论"
      new_follow: "关注这支酒"
      new_photo: "上传了新的图片"
      add_to_cellar: "有人把它加入了酒窖"
    wine:
      new_comment: "有了新的评论" 
      new_follow: "关注这支酒"
      new_photo: "上传了新的图片"
     
       
search_server:
  host: www.sidways.com
  port: 8080
  entry_url: /patrick/query/
  word_url: /patrick/associate
