site: "iWine.com"
rate:
  CNY: 1.00
  HKD: 0.95
  JPY: 0.07
  SGD: 4.95
  USD: 6.37
  GBP: 9.82
  AUD: 6.49
  NZD: 5.21
  EUR: 7.78
  CAD: 6.35
wines:
  capacity:
    750mL: '750'
    620mL: '620'
    500mL: '500'
    375mL: '375'
    250mL: '250'
    187.5mL: '187.5'
    1.5L: '1500'
    2.25L: '2250'
    3L: '3000'
    4.5L: '4500'
    6L: '6000'
    9L: '9000'
    12L: '12000'
    15L: '15000'
    20L: '20000'
    25L: '25000'
    27L: '27000'
    30L: '30000'
    其他:      #设置为空

users:
  cellars:
    item:
      location: [北京, 上海, 香港,广州, 深圳, 其他]
user_profile:
  no_bio: 这个家伙光顾着喝酒，忘记介绍自己了.
  myself_no_bio: 添段话介绍下自己吧！
  configs:
    defaults:
      normal: 1 #默认分享或者所有人可见
      email: [1, 2, 3]
    normal:
      1: 所有人
      2: 我关注的人
    birth_day:
      1: 公开
      2: 完整显示
      3: 只显示星座
      4: 只显示月日
      5: 保密
    message:
      1: <strong>所有人</strong><span></span>
      3: 我关注的人
    recommend:
      1: 在我附近上网的人
      2: 我的MSN／邮箱联系人
      3: 与我有间接关注的人
      4: 与我有共同好友的人
    email:
      1: 我收到一条私信
      2: 我收到一条回复
      3: 我被某人关注
      5: 关于新 iWine 产品功能和技巧的更新
      6: 关于我的 iWine 账号的产品或服务更新
    share:
      1: 默认分享


friends:
  oauth:
    sync_url: /friends/sync
user_oauths:
  setting_type:
    login: 1 #用户通过第三方登陆
    binding: 2 # 用户登录后得绑定操作
    
user_oauths:
  setting_type:
    login: 1 #用户通过第三方登陆
    binding: 2 # 用户登录后得绑定操作

# 图片缩略图
image:
  album:
    x_middle:
      width: 190
      height: 190
    xx_middle:
      width: 150
      height: 150
  user:
    origin:
      width: 280
      height: 280
    large:
      width: 130
      height: 130
    x_middle:
      width: 100
      height: 100
    middle:
      width: 50
      height: 50
    thumb:
      width: 30
      height: 30

  wine_label:
    thumb:
      width: 100
      height: 100
    middle:
      width: 200
      height: 200
    large:
      width: 400
      height: 400
      
  wine:
    xxx_thumb: 
      width: 50
      height: 50
    xx_thumb:
      width: 70
      height: 70
    x_thumb: 
      width: 100
      height: 100
    thumb: 
      width: 130
      height: 130
    middle:
      width: 200
      height: 440
    large:
      width: 440
      height: 440
    large_x:
      width: 610
      height: 640
  winery:
    xxx_thumb: 
      width: 50
      height: 50
    xx_thumb:
      width: 70
      height: 70
    x_thumb:
      width: 100
      height: 100
    thumb: 
      width: 130
      height: 130
    middle:
      width: 200
      height: 200
    middle_x:
      width: 360
      height: 330
    large:
      width: 360
      height: 360
        
timeline:
   event:
    user:
      new_comment: "发表了一条评论"
      new_follow: "关注这支酒"
      new_photo: "上传了新的图片"
      add_to_cellar: "有人把它加入了酒窖"
    wine:
      new_comment: "有了新的评论" 
      new_follow: "关注这支酒"
      new_photo: "上传了新的图片"
     
       
search_server:
  host: 192.168.11.28
  port: 8080
  entry_url: /patrick/query/all
  word_url: /patrick/query/associate
  user_url: /patrick/query/user

search:
  wine:
    variety: ["赤霞珠", "西拉", "梅洛", "黑皮诺", "霞多丽", "长相思", "雷司令"]
    style: ["红葡萄酒", "白葡萄酒", "起泡酒", "粉红葡萄酒"]
    country: ["法国", "意大利", "西班牙", "德国", "奥地利", "澳洲", "新西兰", "智利", "阿根廷", "美国", "南非"]
    hot_area: ["波尔多", "勃艮第", "纳帕谷"]
  winery:
    country: ["法国", "意大利", "西班牙", "德国", "奥地利", "澳洲", "新西兰", "智利", "阿根廷", "美国", "南非"]
    hot_area: ["波尔多", "勃艮第", "纳帕谷"]

photo:
  #1 是label 2是cover 0默认值是普通图片
  photo_type:
    label: 1
    cover: 2
    normal: 0

audit_log:
 status:
   submitted: 0
   approved: 1
   rejected: 2

email:
  developers: ["shanhua.chen@sidways.com", "weston.wei@sidways.com"]
  welcome:
    subject: "注册成功！到各个版块转转吧？"
  follow:
    subject: "恭喜您被人关注了。"
  reply:
    subject: "有人回复您的评论。"
  from:
    normal: "爱红酒 <non-reply@iWine.com>"
    #TODO: 根据不同需要在这里继续添加
  to:
    normal: "non-reply@iWine.com"
    feedback: "suggestion@iwine.com" # 接收用户反馈的邮箱帐号

memcache:
  servers: 
    first: "192.168.11.31"
