sina.com: http://mail.sina.com
vip.sina.com: http://mail.sina.com
yahoo.com.cn: http://cn.mail.yahoo.com
yahoo.com: https://mail.yahoo.com
21cn.com: http://mail.21cn.com
tom.com: http://mail.tom.com
vip.tom.com: http://vip.tom.com
gmail.com: http://mail.google.com/gmail
googlemail.com: http://mail.google.com/gmail
hotmail.com: http://www.Hotmail.com
msn.com: http://www.Hotmail.com
live.com: http://www.Hotmail.com
qq.com: http://mail.qq.com
163.com: http://mail.163.com
126.com: http://mail.126.com
yeah.net: http://www.yeah.net
hexun.com: http://mail.hexun.com
aol.com: https://mail.aol.com
sohu.com: http://mail.sohu.com
mail.com: http://www.mail.com/int
139.com: http://mail.10086.cn
263.net: http://mail.263.net
189.cn: http://webmail28.189.cn/webmail
seed.net.tw: http://webmail.seed.net.tw/Login.do
aim.com: http://mail.aim.com
inbox.com: https://www.inbox.com/login.aspx?gdi=true